// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgGhLiUwUjYZz-UM5SvfGCJIS3WzcjMpo',
    appId: '1:994677489483:web:9ceb85a214762b67e332ce',
    messagingSenderId: '994677489483',
    projectId: 'girlfriend-gpt-by-flutter',
    authDomain: 'girlfriend-gpt-by-flutter.firebaseapp.com',
    storageBucket: 'girlfriend-gpt-by-flutter.appspot.com',
    measurementId: 'G-CTXQCG5FD3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDz2sFLWtXnbY4qxu0egmOahHH8ZsvXV0',
    appId: '1:994677489483:android:0532d9638ca94513e332ce',
    messagingSenderId: '994677489483',
    projectId: 'girlfriend-gpt-by-flutter',
    storageBucket: 'girlfriend-gpt-by-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsLbUWw8wsmMzZb8EGu3kj2odJ-KPnLvQ',
    appId: '1:994677489483:ios:74a3ad19a212c73ee332ce',
    messagingSenderId: '994677489483',
    projectId: 'girlfriend-gpt-by-flutter',
    storageBucket: 'girlfriend-gpt-by-flutter.appspot.com',
    iosClientId: '994677489483-flvtcfllo34lkilmrlojc308tdmugllj.apps.googleusercontent.com',
    iosBundleId: 'com.example.girlfriendGpt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsLbUWw8wsmMzZb8EGu3kj2odJ-KPnLvQ',
    appId: '1:994677489483:ios:a018643aef385f7ee332ce',
    messagingSenderId: '994677489483',
    projectId: 'girlfriend-gpt-by-flutter',
    storageBucket: 'girlfriend-gpt-by-flutter.appspot.com',
    iosClientId: '994677489483-op1923e38vut2fsnmt3rj84hudang3mj.apps.googleusercontent.com',
    iosBundleId: 'com.example.girlfriendGpt.RunnerTests',
  );
}
